export default {
  SET_COMMENT_EXPRESS: 'SET_COMMENT_EXPRESS',
  SET_COMMENT_PARAMS: 'SET_COMMENT_PARAMS',
  SET_COMMENT_FILTER: 'SET_COMMENT_FILTER',
  FETCH_LIST_COMMENT: 'FETCH_LIST_COMMENT',
  SET_COMMENT_DATA: 'SET_COMMENT_DATA'
}
