export default {
  SET_EXPRESS_PARAMS: 'SET_EXPRESS_PARAMS',
  SET_EXPRESS_FILTER: 'SET_EXPRESS_FILTER',
  FETCH_LIST_EXPRESS: 'FETCH_LIST_EXPRESS',
  SET_EXPRESS_ACTIVE_ID: 'SET_EXPRESS_ACTIVE_ID',
  SET_EXPRESS_DETAIL: 'SET_EXPRESS_DETAIL',
  SET_EXPRESS_DATA: 'SET_EXPRESS_DATA'
}
